### ISSUE TITLE
Missing keyboard shortcut to quit changelog view

### ISSUE THREAD

**Issue by rchl** [jdeniau/changelog-view#10]
Either there is no shortcut to quit the changelog view or I was not able to find it. It would be convenient to have `esc` and/or `q` to exit the view.

I can press ctrl+c but that feels like force-killing the app.

**Comment by jdeniau** [comment]
You are right, the only way to quit now is to press `CTRL-C`. 

I will add a "real" exit key

**Comment by jdeniau** [comment]
Fixed in 1.10.0.

Thanks for the report !
